name: My Demo Workflow

on: [workflow_dispatch]

jobs:
  hello-world:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: ./.github/actions/demo-action
      - run: echo "Hej WürthIT 🥳"

  hello-world-2:
    name: Hello World Job 2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hej WürthIT 🥳"
      
  hello-world-3:
    name: Hello World Job 3
    runs-on: ubuntu-latest
    needs: [hello-world, hello-world-2]
    steps:
      - run: echo "Hej WürthIT 🥳"
